; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = ttgo-lora32-v21
framework = espidf
monitor_speed = 115200

[env:btn_led]
build_flags = -DROLE_BTN_LED

[env:led_lora]
build_flags = -DROLE_LED_LORA
